"""add game models

Revision ID: 74b068f5fcf3
Revises:
Create Date: 2026-02-21 16:38:54.013728

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "74b068f5fcf3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
